# simulation
gui: false
max_steps: 5400
n_cars_generated: 1000
episode_seed: 10000
yellow_duration: 4
green_duration: 10

# agent
state_size: 80
num_actions: 4
gamma: 0.75

# paths
sumocfg_file: intersection/sumo_config.sumocfg
model_to_test: 2
