# simulation
gui: false
total_episodes: 100
max_steps: 5400
n_cars_generated: 1000
green_duration: 10
yellow_duration: 4
turn_chanche: 0.25

# model
num_layers: 4
width_layers: 400
batch_size: 100
learning_rate: 0.001
training_epochs: 800

# memory
memory_size_min: 600
memory_size_max: 50000

# agent
state_size: 80
num_actions: 4
gamma: 0.75

# paths
sumocfg_file: intersection/sumo_config.sumocfg
