# simulation
gui: true
max_steps: 5400
n_cars_generated: 1000
episode_seed: 10000
yellow_duration: 4
green_duration: 10

# agent
num_states: 80
num_actions: 4
gamma: 0.75

# paths
models_path: models
sumocfg_file: sumo_config.sumocfg
model_to_test: 2
